import './style.css'
import './receitas.css'
import './estoque.css'
import './visual-teste.css'
import { supabase } from './supabase.js'
import { criarModuloReceitas } from './receitas.js'
import { criarModuloEstoque } from './estoque.js'

const $=s=>document.querySelector(s),money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}),bd=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'',today=()=>new Date().toISOString().slice(0,10)
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const pe=p=>p==='Growler de vinho'?'🍷':p==='Barril reserva'?'🛢️':'🍺',products=['Barril','Growler de vinho','Growler de Pilsen','Barril reserva']
let session=null,brewery=null,page='dashboard',modal=null,editing=null,items=[],channel=null,tema=localStorage.getItem('tema-ze-parroti')||'claro',maisAberto=false,data={movimentacoes:[],entregas:[],contas_pagar:[],valores_receber:[]}
const app=$('#app'),status=(x,k)=>x.status==='Pago'?'Pago':x[k]<today()?'Atrasado':'Pendente',empty=()=>'<div class="empty">Nenhum registro cadastrado</div>'
const moduloReceitas=criarModuloReceitas({supabase,getCervejaria:()=>brewery.cervejaria_id,getUsuario:()=>session.user.id,escapeHtml:esc})
const moduloEstoque=criarModuloEstoque({supabase,getCervejaria:()=>brewery.cervejaria_id,getUsuario:()=>session.user.id,escapeHtml:esc})


function aplicarTema(){document.documentElement.dataset.theme=tema}
window.alternarTema=()=>{tema=tema==='claro'?'escuro':'claro';localStorage.setItem('tema-ze-parroti',tema);aplicarTema();render()}
window.toggleMais=()=>{maisAberto=!maisAberto;document.querySelector('#mobileMore')?.classList.toggle('open',maisAberto)}
function alertasHtml(){const atrasadas=data.contas_pagar.filter(x=>status(x,'data_vencimento')==='Atrasado').length,hoje=data.entregas.filter(x=>x.data_entrega===today()).length,devedores=data.valores_receber.filter(x=>status(x,'data_combinada')==='Atrasado').length,a=[];if(atrasadas)a.push(`🔴 ${atrasadas} conta(s) atrasada(s)`);if(hoje)a.push(`🚚 ${hoje} entrega(s) para hoje`);if(devedores)a.push(`👥 ${devedores} recebimento(s) atrasado(s)`);return `<section class="alerts-panel"><div><b>⚠️ Atenção</b><small>Resumo rápido da operação</small></div><div class="alert-chips">${a.length?a.map(x=>`<span>${x}</span>`).join(''):'<span class="ok">✅ Nenhuma pendência importante</span>'}</div></section>`}
function buscaHtml(){return `<div class="view-tools"><label>🔎<input id="viewSearch" placeholder="Pesquisar nesta aba"></label></div>`}
function ativarBusca(){const i=$('#viewSearch');if(!i)return;i.oninput=()=>{const q=i.value.toLowerCase().trim();document.querySelectorAll('#content .row,#content .stock-card,#content .receita-card').forEach(x=>x.style.display=x.textContent.toLowerCase().includes(q)?'':'none')}}
function mobileNavHtml(){const maisAtivo=['receive','stock','recipes'].includes(page);return `<nav class="mobile-nav"><button class="${page==='dashboard'?'on':''}" onclick="go('dashboard')">📊<small>Início</small></button><button class="${page==='deliveries'?'on':''}" onclick="go('deliveries')">🚚<small>Entregas</small></button><button class="${page==='finance'?'on':''}" onclick="go('finance')">💰<small>Financeiro</small></button><button class="${page==='bills'?'on':''}" onclick="go('bills')">📅<small>Contas</small></button><button class="${maisAtivo?'on':''}" onclick="toggleMais()">☰<small>Mais</small></button></nav><div class="mobile-more" id="mobileMore"><button class="${page==='receive'?'on':''}" onclick="go('receive')">👥 Clientes devendo</button><button class="${page==='stock'?'on':''}" onclick="go('stock')">📦 Estoque</button><button class="${page==='recipes'?'on':''}" onclick="go('recipes')">📖 Receitas</button><button onclick="logout()">🚪 Sair</button></div>`}

async function start(){aplicarTema();session=(await supabase.auth.getSession()).data.session;if(session)await enter();else login();supabase.auth.onAuthStateChange(async(_,s)=>{session=s;if(s)await enter();else login()})}
function login(){app.innerHTML=`<div class="login"><form class="loginbox" id="login"><img class="login-logo" src="/logo-ze-parroti.jpg" alt="Logo Zé Parroti"><h1>Gestão Zé Parroti</h1><p>Entre para acessar os dados compartilhados.</p><label class="field">E-mail<input name="email" type="email" required></label><label class="field">Senha<input name="password" type="password" required></label><p class="error" id="err"></p><button class="btn full">Entrar</button></form></div>`;$('#login').onsubmit=async e=>{e.preventDefault();let f=new FormData(e.target),{error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)$('#err').textContent=error.message}}
async function enter(){let{data:m}=await supabase.from('usuarios_cervejaria').select('cervejaria_id,nome,funcao,cervejarias(nome)').eq('usuario_id',session.user.id).limit(1).maybeSingle();if(!m){app.innerHTML='<div class="login"><div class="loginbox"><h2>Acesso não vinculado</h2><button class="btn" onclick="logout()">Sair</button></div></div>';return}brewery=m;await load();subscribe();render()}
async function load(){let id=brewery.cervejaria_id,rs=await Promise.all([supabase.from('movimentacoes').select('*').eq('cervejaria_id',id).order('data',{ascending:false}),supabase.from('entregas').select('*,entrega_itens(*)').eq('cervejaria_id',id).order('data_entrega'),supabase.from('contas_pagar').select('*').eq('cervejaria_id',id).order('data_vencimento'),supabase.from('valores_receber').select('*').eq('cervejaria_id',id).order('data_combinada')]);['movimentacoes','entregas','contas_pagar','valores_receber'].forEach((k,i)=>data[k]=rs[i].data||[]);let bad=rs.find(r=>r.error);if(bad)alert(bad.error.message)}
function subscribe(){if(channel)supabase.removeChannel(channel);channel=supabase.channel('gestao').on('postgres_changes',{event:'*',schema:'public'},async()=>{await load();render()}).subscribe()}
window.logout=()=>supabase.auth.signOut();window.go=p=>{page=p;render()}
const pages={dashboard:'📊 Dashboard',finance:'💰 Financeiro',deliveries:'🚚 Entregas',bills:'📅 Contas a pagar',receive:'👥 Clientes devendo',recipes:'📖 Receitas',stock:'📦 Estoque'}
function metric(t,v,e,cl=''){return`<div class="card metric"><div><small>${t}</small><strong class="${cl}">${v}</strong></div><span class="emoji">${e}</span></div>`}
function act(k,x){return`<div class="actions"><button onclick="editRow('${k}','${x.id}')">✎</button><button onclick="delRow('${k}','${x.id}')">🗑</button></div>`}
function render(){app.innerHTML=`<header class="top"><span class="brand"><img class="header-logo" src="/logo-ze-parroti.jpg" alt="Logo Zé Parroti"> Gestão Zé Parroti</span><div class="user-area"><span><b>${esc(brewery?.nome||session?.user?.email||'Usuário')}</b><small>${esc(brewery?.funcao||'')}</small></span><button class="theme-btn" onclick="alternarTema()">${tema==='claro'?'🌙':'☀️'}</button><button class="btn alt desktop-only" onclick="logout()">Sair</button></div></header><nav class="tabs">${Object.entries(pages).map(([k,v])=>`<button class="${page===k?'on':''}" onclick="go('${k}')">${v}</button>`).join('')}</nav><main class="main"><div class="head"><h1>${pages[page]}</h1>${!['dashboard','recipes','stock'].includes(page)?'<button class="btn" id="add">＋ Adicionar</button>':''}</div><div id="content"></div></main>${mobileNavHtml()}`;let telas={dashboard,finance,deliveries,bills,receive:receivables,recipes:()=>moduloReceitas.abrir($('#content')),stock:()=>moduloEstoque.abrir($('#content'))};telas[page]();setTimeout(()=>{if(page!=='dashboard'){const c=$('#content');if(c&&!c.querySelector('.view-tools'))c.insertAdjacentHTML('afterbegin',buscaHtml());ativarBusca()}},180);if($('#add'))$('#add').onclick=()=>openModal(page)}
function preview(t,a,fn){return`<div class="card"><div class="section-head"><h3>${t}</h3></div><div class="preview">${a.slice(0,10).map(fn).join('')||empty()}</div><small>Exibindo até 10 itens</small></div>`}
function dashboard(){let bal=data.movimentacoes.reduce((a,x)=>a+(x.tipo==='Entrada'?+x.valor:-x.valor),0),bs=data.contas_pagar.filter(x=>status(x,'data_vencimento')!=='Pago'),rs=data.valores_receber.filter(x=>status(x,'data_combinada')!=='Pago');$('#content').innerHTML=alertasHtml()+`<div class="metrics">${metric('Saldo em conta',money(bal),'💰')}${metric('Próximas entregas',data.entregas.length,'🍺')}${metric('Contas a pagar',money(bs.reduce((a,x)=>a+(+x.valor),0)),'📅','redtext')}${metric('Valores a receber',money(rs.reduce((a,x)=>a+(+x.valor),0)),'💵')}</div><div class="dashboard-grid">${preview('🚚 Próximas entregas',data.entregas,x=>deliveryRow(x,false))}${preview('📅 Contas a pagar',bs,x=>`<div class="row"><div class="grow"><b>${esc(x.descricao)}</b><small>${bd(x.data_vencimento)} • ${status(x,'data_vencimento')}</small></div><b class="redtext">${money(x.valor)}</b></div>`)}${preview('👥 Clientes devendo',rs,x=>`<div class="row"><div class="grow"><b>${esc(x.cliente)}</b><small>${esc(x.descricao)}</small></div><b>${money(x.valor)}</b></div>`)}</div>`;let area=document.createElement('div');area.id='stockDashboard';$('#content').appendChild(area);moduloEstoque.dashboardHtml().then(h=>{if($('#stockDashboard'))$('#stockDashboard').innerHTML=h})}
function finance(){let bal=data.movimentacoes.reduce((a,x)=>a+(x.tipo==='Entrada'?+x.valor:-x.valor),0);$('#content').innerHTML=metric('Saldo em conta',money(bal),'💰')+data.movimentacoes.map(x=>`<div class="row"><div class="grow"><b>${x.tipo==='Entrada'?'🟢':'🔴'} ${esc(x.descricao)}</b><small>${bd(x.data)} • ${x.tipo}</small></div><b>${x.tipo==='Entrada'?'+':'-'} ${money(x.valor)}</b>${act('finance',x)}</div>`).join('')}
function chips(x){return`<div class="chips">${(x.entrega_itens||[]).map(i=>`<span class="chip">${pe(i.produto)} ${esc(i.produto)} • ${i.quantidade} un. • ${i.litros} L</span>`).join('')}</div>`}
function deliveryRow(x,a=true){return`<div class="row"><div class="grow"><b>🚚 ${esc(x.cliente)}</b><small>${bd(x.data_entrega)} às ${x.horario_entrega?.slice(0,5)} • 📍 ${esc(x.local_entrega)}</small>${chips(x)}</div><b>${money(x.valor)}</b>${a?act('deliveries',x):''}</div>`}
function deliveries(){$('#content').innerHTML=data.entregas.map(x=>deliveryRow(x)).join('')||empty()}
function debt(k,x,dk){let st=status(x,dk);return`<div class="row"><div class="grow"><b>${k==='receive'?'👤 '+esc(x.cliente):'🧾 '+esc(x.descricao)} <span class="status ${st==='Pago'?'paid':st==='Atrasado'?'late':''}">${st}</span></b><small>${k==='receive'?esc(x.descricao)+' • ':''}${bd(x[dk])}</small></div><b class="${k==='bills'?'redtext':''}">${money(x.valor)}</b>${st!=='Pago'?`<button onclick="pay('${k}','${x.id}')">✓ ${k==='receive'?'Recebido':'Pago'}</button>`:''}${act(k,x)}</div>`}
function bills(){$('#content').innerHTML=data.contas_pagar.map(x=>debt('bills',x,'data_vencimento')).join('')||empty()}
function receivables(){$('#content').innerHTML=data.valores_receber.map(x=>debt('receive',x,'data_combinada')).join('')||empty()}
const cfg={finance:{table:'movimentacoes',fields:[['data','Data','date'],['descricao','Descrição','text'],['valor','Valor','number'],['tipo','Tipo','select',['Entrada','Saida']]]},bills:{table:'contas_pagar',fields:[['descricao','Descrição','text'],['valor','Valor','number'],['data_vencimento','Vencimento','date'],['status','Status','select',['Pendente','Pago','Atrasado']]]},receive:{table:'valores_receber',fields:[['cliente','Cliente','text'],['descricao','Descrição','text'],['valor','Valor','number'],['data_combinada','Data combinada','date'],['status','Status','select',['Pendente','Pago','Atrasado']]]},deliveries:{table:'entregas',fields:[['cliente','Cliente','text'],['data_entrega','Data','date'],['horario_entrega','Horário','time'],['valor','Valor','number'],['local_entrega','Local','text']]}}
function field(k,l,t,opts,v){if(t==='select')return`<label class="field">${l}<select name="${k}">${opts.map(o=>`<option ${v===o?'selected':''}>${o}</option>`).join('')}</select></label>`;return`<label class="field ${['cliente','descricao','local_entrega'].includes(k)?'full':''}">${l}<input name="${k}" type="${t}" step="0.01" value="${esc(v??'')}"></label>`}
function itemEditor(){return`<div class="full"><b>📦 Itens do pedido</b><button type="button" class="btn alt" onclick="addItem()">+ Item</button><div id="items">${items.map(itemHtml).join('')}</div></div>`}
function itemHtml(x,i){return`<div class="item"><select onchange="setItem(${i},'produto',this.value)">${products.map(p=>`<option ${p===x.produto?'selected':''}>${p}</option>`).join('')}</select><input type="number" value="${x.quantidade}" onchange="setItem(${i},'quantidade',this.value)"><input type="number" value="${x.litros}" onchange="setItem(${i},'litros',this.value)"><button type="button" onclick="removeItem(${i})">🗑</button></div>`}
function openModal(k,obj={}){modal=k;editing=obj.id||null;items=k==='deliveries'?(obj.entrega_itens||[]).map(i=>({produto:i.produto,quantidade:i.quantidade,litros:i.litros})):[];if(k==='deliveries'&&!items.length)items=[{produto:'Barril',quantidade:1,litros:50}];let c=cfg[k];document.body.insertAdjacentHTML('beforeend',`<div class="modalbg" id="modal"><form class="modal" id="form"><h2>${editing?'Editar':'Adicionar'} registro</h2><div class="formgrid">${c.fields.map(f=>field(...f,obj[f[0]])).join('')}${k==='deliveries'?itemEditor():''}</div><p class="error" id="formerr"></p><div class="modalactions"><button type="button" class="btn alt" onclick="closeModal()">Cancelar</button><button class="btn">Salvar</button></div></form></div>`);$('#form').onsubmit=save}
window.addItem=()=>{items.push({produto:'Barril',quantidade:1,litros:50});$('#items').innerHTML=items.map(itemHtml).join('')};window.setItem=(i,k,v)=>items[i][k]=v;window.removeItem=i=>{items.splice(i,1);$('#items').innerHTML=items.map(itemHtml).join('')};window.closeModal=()=>$('#modal')?.remove()
async function save(e){e.preventDefault();let c=cfg[modal],f=new FormData(e.target),obj={cervejaria_id:brewery.cervejaria_id,usuario_id:session.user.id};for(let[k]of c.fields)obj[k]=f.get(k)||null;if(modal==='deliveries'){obj.litros=items.reduce((a,i)=>a+(+i.litros||0),0);obj.barril_reserva=items.some(i=>i.produto==='Barril reserva');obj.litros_barril_reserva=items.filter(i=>i.produto==='Barril reserva').reduce((a,i)=>a+(+i.litros||0),0)||null}let q=editing?supabase.from(c.table).update(obj).eq('id',editing).select().single():supabase.from(c.table).insert(obj).select().single(),{data:saved,error}=await q;if(error){$('#formerr').textContent=error.message;return}if(modal==='deliveries'){await supabase.from('entrega_itens').delete().eq('entrega_id',saved.id);let rows=items.map(i=>({entrega_id:saved.id,cervejaria_id:brewery.cervejaria_id,usuario_id:session.user.id,produto:i.produto,quantidade:+i.quantidade,litros:+i.litros}));if(rows.length){let{error:e2}=await supabase.from('entrega_itens').insert(rows);if(e2){$('#formerr').textContent=e2.message;return}}}closeModal();await load();render()}
window.editRow=(k,id)=>{let c=cfg[k],obj=data[c.table].find(x=>x.id===id);openModal(k,obj)};window.delRow=async(k,id)=>{if(!confirm('Apagar este registro?'))return;let{error}=await supabase.from(cfg[k].table).delete().eq('id',id);if(error)alert(error.message);else{await load();render()}};window.pay=async(k,id)=>{let obj=k==='receive'?{status:'Pago',data_recebimento:today()}:{status:'Pago',data_pagamento:today()};await supabase.from(cfg[k].table).update(obj).eq('id',id);await load();render()}
start()
