import './style.css'
import {supabase} from './supabase.js'
const $=s=>document.querySelector(s), money=v=>Number(v||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'}), brdate=v=>v?new Date(v+'T12:00:00').toLocaleDateString('pt-BR'):'', today=()=>new Date().toISOString().slice(0,10)
let session=null, brewery=null, data={movimentacoes:[],entregas:[],contas_pagar:[],valores_receber:[]}, page='dashboard', modal=null, editing=null, channel=null
const app=$('#app')
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function errorText(e){return e?.message||'Ocorreu um erro'}
async function start(){const {data:{session:s}}=await supabase.auth.getSession(); session=s; if(session) await enter(); else login(); supabase.auth.onAuthStateChange(async(_e,s)=>{session=s;if(s)await enter();else login()})}
function login(){app.innerHTML=`<div class="login"><form class="loginbox" id="login"><h1>🍺 Minha Cervejaria</h1><p>Entre para acessar os dados compartilhados.</p><label class="field">E-mail<input name="email" type="email" required></label><label class="field">Senha<input name="password" type="password" required></label><p class="error" id="err"></p><button class="btn full">Entrar</button></form></div>`;$('#login').onsubmit=async e=>{e.preventDefault();$('#err').textContent='Entrando...';const f=new FormData(e.target),{error}=await supabase.auth.signInWithPassword({email:f.get('email'),password:f.get('password')});if(error)$('#err').textContent='Não foi possível entrar: '+error.message}}
async function enter(){const {data:m,error}=await supabase.from('usuarios_cervejaria').select('cervejaria_id,nome,funcao,cervejarias(nome)').eq('usuario_id',session.user.id).limit(1).maybeSingle();if(error||!m){app.innerHTML=`<div class="login"><div class="loginbox"><h2>Acesso não vinculado</h2><p>Este usuário existe, mas ainda não está ligado à cervejaria.</p><p class="error">${esc(errorText(error))}</p><button class="btn" onclick="window.logout()">Sair</button></div></div>`;return}brewery=m;await load();subscribe();render()}
async function load(){const id=brewery.cervejaria_id;const qs=[supabase.from('movimentacoes').select('*').eq('cervejaria_id',id).order('data',{ascending:false}),supabase.from('entregas').select('*').eq('cervejaria_id',id).order('data_entrega'),supabase.from('contas_pagar').select('*').eq('cervejaria_id',id).order('data_vencimento'),supabase.from('valores_receber').select('*').eq('cervejaria_id',id).order('data_combinada')];const rs=await Promise.all(qs);['movimentacoes','entregas','contas_pagar','valores_receber'].forEach((k,i)=>data[k]=rs[i].data||[]);const bad=rs.find(r=>r.error);if(bad)alert(errorText(bad.error))}
function subscribe(){if(channel)supabase.removeChannel(channel);channel=supabase.channel('cervejaria').on('postgres_changes',{event:'*',schema:'public'},async()=>{await load();render()}).subscribe()}
window.logout=()=>supabase.auth.signOut(); window.go=p=>{page=p;render()};
const title={dashboard:'Dashboard',finance:'Financeiro',deliveries:'Entregas',bills:'Contas a pagar',receive:'Clientes devendo'}
function status(x,dateKey){if(x.status==='Pago')return'Pago';return x[dateKey]<today()?'Atrasado':'Pendente'}
function render(){app.innerHTML=`<div class="layout"><header class="top"><span class="brand">🍺 ${esc(brewery.cervejarias?.nome||'Minha Cervejaria')}</span><button class="btn alt" onclick="logout()">Sair</button></header><nav class="tabs">${[['dashboard','Dashboard'],['finance','Financeiro'],['deliveries','Entregas'],['bills','Contas a pagar'],['receive','Clientes devendo']].map(x=>`<button class="${page===x[0]?'on':''}" onclick="go('${x[0]}')">${x[1]}</button>`).join('')}</nav><main class="main"><div class="head"><h1>${title[page]}</h1>${page!=='dashboard'?`<button class="btn" id="add">＋ Adicionar</button>`:''}</div><div id="content"></div></main></div>`;if(page==='dashboard')dashboard();if(page==='finance')finance();if(page==='deliveries')deliveries();if(page==='bills')bills();if(page==='receive')receivables();if($('#add'))$('#add').onclick=()=>openModal(page)}
function dashboard(){let bal=data.movimentacoes.reduce((a,x)=>a+(x.tipo==='Entrada'?+x.valor:-x.valor),0),bills=data.contas_pagar.filter(x=>status(x,'data_vencimento')!=='Pago'),rec=data.valores_receber.filter(x=>status(x,'data_combinada')!=='Pago');$('#content').innerHTML=`<div class="metrics"><div class="card metric"><small>Saldo em conta</small><strong>${money(bal)}</strong></div><div class="card metric"><small>Próximas entregas</small><strong>${data.entregas.length}</strong></div><div class="card metric"><small>Contas a pagar</small><strong>${money(bills.reduce((a,x)=>a+(+x.valor),0))}</strong></div><div class="card metric"><small>Valores a receber</small><strong>${money(rec.reduce((a,x)=>a+(+x.valor),0))}</strong></div></div><div class="grid"><div class="card"><h3>Próximas entregas</h3>${data.entregas.slice(0,5).map(x=>`<div class="row"><div class="grow"><b>${esc(x.cliente)}</b><small>${brdate(x.data_entrega)} às ${x.horario_entrega?.slice(0,5)} • ${x.litros} L • ${esc(x.local_entrega)}${x.barril_reserva?` • Reserva ${x.litros_barril_reserva} L`:''}</small></div><b>${money(x.valor)}</b></div>`).join('')||empty()}</div><div class="card"><h3>Clientes devendo</h3>${rec.slice(0,5).map(x=>`<div class="row"><div class="grow"><b>${esc(x.cliente)}</b><small>${esc(x.descricao)}</small></div><b>${money(x.valor)}</b></div>`).join('')||empty()}</div></div>`}
function actions(kind,x){return `<div class="actions"><button onclick="window.edit('${kind}','${x.id}')">✎</button><button onclick="window.del('${kind}','${x.id}')">🗑</button></div>`}
function finance(){let bal=data.movimentacoes.reduce((a,x)=>a+(x.tipo==='Entrada'?+x.valor:-x.valor),0);$('#content').innerHTML=`<div class="card metric"><small>Saldo em conta</small><strong>${money(bal)}</strong></div>${data.movimentacoes.map(x=>`<div class="row"><div class="grow"><b>${esc(x.descricao)}</b><small>${brdate(x.data)} • ${x.tipo}</small></div><b>${x.tipo==='Entrada'?'+':'-'} ${money(x.valor)}</b>${actions('finance',x)}</div>`).join('')||empty()}`}
function deliveries(){$('#content').innerHTML=data.entregas.map(x=>`<div class="row"><div class="grow"><b>${esc(x.cliente)}</b><small>${brdate(x.data_entrega)} às ${x.horario_entrega?.slice(0,5)} • ${x.litros} L • ${esc(x.local_entrega)}${x.barril_reserva?` • Barril reserva ${x.litros_barril_reserva} L`:''}</small></div><b>${money(x.valor)}</b>${actions('deliveries',x)}</div>`).join('')||empty()}
function bills(){$('#content').innerHTML=data.contas_pagar.map(x=>rowDebt('bills',x,'data_vencimento')).join('')||empty()}
function receivables(){$('#content').innerHTML=data.valores_receber.map(x=>rowDebt('receive',x,'data_combinada')).join('')||empty()}
function rowDebt(kind,x,dk){let st=status(x,dk);return `<div class="row"><div class="grow"><b>${esc(x.cliente||x.descricao)} <span class="status ${st==='Pago'?'paid':st==='Atrasado'?'late':''}">${st}</span></b><small>${esc(x.cliente?x.descricao:'')} • ${brdate(x[dk])}</small></div><b>${money(x.valor)}</b>${st!=='Pago'?`<button onclick="window.pay('${kind}','${x.id}')">✓ ${kind==='receive'?'Recebido':'Pago'}</button>`:''}${actions(kind,x)}</div>`}
function empty(){return '<div class="empty">Nenhum registro cadastrado</div>'}
const config={finance:{table:'movimentacoes',fields:[['data','Data','date'],['descricao','Descrição','text'],['valor','Valor','number'],['tipo','Tipo','select',['Entrada','Saida']]]},deliveries:{table:'entregas',fields:[['cliente','Cliente','text'],['data_entrega','Data','date'],['horario_entrega','Horário','time'],['litros','Litros','number'],['valor','Valor','number'],['local_entrega','Local','text'],['barril_reserva','Barril reserva','checkbox'],['litros_barril_reserva','Litros reserva','number']]},bills:{table:'contas_pagar',fields:[['descricao','Descrição','text'],['valor','Valor','number'],['data_vencimento','Vencimento','date'],['status','Status','select',['Pendente','Pago','Atrasado']],['data_pagamento','Data pagamento','date']]},receive:{table:'valores_receber',fields:[['cliente','Cliente','text'],['descricao','Descrição','text'],['valor','Valor','number'],['data_combinada','Data combinada','date'],['status','Status','select',['Pendente','Pago','Atrasado']],['data_recebimento','Data recebimento','date']]}}
function openModal(kind,obj={}){modal=kind;editing=obj.id||null;let c=config[kind];document.body.insertAdjacentHTML('beforeend',`<div class="modalbg" id="modal"><form class="modal" id="form"><h2>${editing?'Editar':'Adicionar'} registro</h2><div class="formgrid">${c.fields.map(([k,l,t,opts])=>field(k,l,t,opts,obj[k])).join('')}</div><p class="error" id="formerr"></p><div class="modalactions"><button type="button" class="btn alt" id="cancel">Cancelar</button><button class="btn">Salvar</button></div></form></div>`);$('#cancel').onclick=close;$('#form').onsubmit=save}
function field(k,l,t,opts,v){if(t==='select')return `<label class="field">${l}<select name="${k}">${opts.map(o=>`<option ${v===o?'selected':''}>${o}</option>`).join('')}</select></label>`;if(t==='checkbox')return `<label class="field full"><input name="${k}" type="checkbox" ${v?'checked':''}> ${l}</label>`;return `<label class="field ${['descricao','cliente','local_entrega'].includes(k)?'full':''}">${l}<input name="${k}" type="${t}" step="0.01" value="${esc(v??'')}"></label>`}
function close(){document.querySelector('#modal')?.remove();modal=null;editing=null}
async function save(e){e.preventDefault();let c=config[modal],f=new FormData(e.target),obj={cervejaria_id:brewery.cervejaria_id,usuario_id:session.user.id};for(const [k,,t] of c.fields)obj[k]=t==='checkbox'?f.get(k)==='on':f.get(k)||null;let q=editing?supabase.from(c.table).update(obj).eq('id',editing):supabase.from(c.table).insert(obj),{error}=await q;if(error){$('#formerr').textContent=errorText(error);return}close();await load();render()}
window.edit=(kind,id)=>{let c=config[kind],obj=data[c.table].find(x=>x.id===id);openModal(kind,obj)}
window.del=async(kind,id)=>{if(!confirm('Apagar este registro?'))return;let c=config[kind],{error}=await supabase.from(c.table).delete().eq('id',id);if(error)alert(errorText(error));else{await load();render()}}
window.pay=async(kind,id)=>{let c=config[kind],obj=kind==='receive'?{status:'Pago',data_recebimento:today()}:{status:'Pago',data_pagamento:today()},{error}=await supabase.from(c.table).update(obj).eq('id',id);if(error)alert(errorText(error));else{await load();render()}}
start()
