export function criarModuloReceitas({supabase,getCervejaria,getUsuario,escapeHtml,onVoltar}){
 const produtosVazios=()=>({nome:'',quantidade:''});
 const nova=()=>({nome:'',estilo:'',volume_lote:'',agua_mostura:'',agua_lavagem:'',fermento_nome:'',fermento_pacotes:'',mash_out_temperatura:'',mash_out_tempo:'',lavagem_temperatura:'',lavagem_tempo:'',fervura_tempo:'',maltes:[produtosVazios()],lupulos:[produtosVazios()],adjuntos:[],correcoes:[produtosVazios()],rampas:[{temperatura:'',tempo_minutos:''}],adicoes:[]});
 let receitas=[],form=nova(),etapa=0,editando=null;
 const $=s=>document.querySelector(s), n=v=>Number(v||0), eh=id=>document.getElementById(id);
 async function carregar(){const cid=getCervejaria();const {data,error}=await supabase.from('receitas').select('*,receita_ingredientes(*),receita_rampas(*),receita_fervura_adicoes(*)').eq('cervejaria_id',cid).order('nome');if(error)throw error;receitas=data||[];}
 function mapear(r){return{...r,maltes:(r.receita_ingredientes||[]).filter(x=>x.categoria==='Malte').map(x=>({nome:x.nome,quantidade:x.quantidade})),lupulos:(r.receita_ingredientes||[]).filter(x=>x.categoria==='Lupulo').map(x=>({nome:x.nome,quantidade:x.quantidade})),adjuntos:(r.receita_ingredientes||[]).filter(x=>x.categoria==='Adjunto').map(x=>({nome:x.nome,quantidade:x.quantidade})),correcoes:(r.receita_ingredientes||[]).filter(x=>x.categoria==='CorrecaoAgua').map(x=>({nome:x.nome,quantidade:x.quantidade})),rampas:[...(r.receita_rampas||[])].sort((a,b)=>a.ordem-b.ordem),adicoes:[...(r.receita_fervura_adicoes||[])].sort((a,b)=>b.minutos_para_fim-a.minutos_para_fim)};}
 async function abrir(container){await carregar();renderLista(container);}
 function renderLista(c){c.innerHTML=`<div class="receitas-head"><button class="btn" id="novaReceita">＋ Nova receita</button></div><div class="receitas-grid">${receitas.map(r=>`<article class="receita-card"><button class="receita-abrir" data-id="${r.id}"><small>${escapeHtml(r.estilo||'Sem estilo')}</small><h2>🍺 ${escapeHtml(r.nome)}</h2><span>${r.volume_lote||0} L</span><div><b>💧 ${n(r.agua_mostura)+n(r.agua_lavagem)} L</b><b>♨️ ${r.fervura_tempo||0} min</b></div></button><div class="receita-acoes"><button type="button" class="receita-editar" data-id="${r.id}">✎ Editar</button><button type="button" class="receita-apagar" data-id="${r.id}">🗑 Apagar</button></div></article>`).join('')||'<div class="empty">Nenhuma receita cadastrada</div>'}</div>`;eh('novaReceita').onclick=()=>abrirForm(c);c.querySelectorAll('.receita-abrir').forEach(b=>b.onclick=()=>visualizarReceita(c,mapear(receitas.find(r=>r.id===b.dataset.id))));c.querySelectorAll('.receita-editar').forEach(b=>b.onclick=()=>abrirForm(c,mapear(receitas.find(r=>r.id===b.dataset.id))));c.querySelectorAll('.receita-apagar').forEach(b=>b.onclick=()=>apagarReceita(c,b.dataset.id));}
 function visualizarReceita(c,r){
 const lista=(titulo,itens,unidade)=>`<section class="view-block"><h3>${titulo}</h3>${itens.length?itens.map(x=>`<div class="view-line"><span>${escapeHtml(x.nome||x.ingrediente||'')}</span><b>${x.quantidade} ${x.unidade||unidade}</b></div>`).join(''):'<p class="view-empty">Nenhum item cadastrado</p>'}</section>`;
 const rampas=[...(r.rampas||[])].sort((a,b)=>(a.ordem||0)-(b.ordem||0));
 const adicoes=[...(r.adicoes||[])].sort((a,b)=>Number(b.minutos_para_fim)-Number(a.minutos_para_fim));
 c.innerHTML=`<div class="recipe-view"><div class="recipe-view-head"><div><small>FICHA TÉCNICA</small><h2>🍺 ${escapeHtml(r.nome)}</h2><p>${escapeHtml(r.estilo||'Sem estilo informado')}</p></div><div class="recipe-view-actions"><button class="btn alt" id="voltarReceitas">← Voltar</button><button class="btn" id="editarReceitaView">✎ Editar</button></div></div>
 <div class="view-summary"><div><small>Volume do lote</small><b>${r.volume_lote||0} L</b></div><div><small>Água total</small><b>${n(r.agua_mostura)+n(r.agua_lavagem)} L</b></div><div><small>Tempo de fervura</small><b>${r.fervura_tempo||0} min</b></div></div>
 <div class="view-grid">
  <section class="view-block"><h3>💧 Água</h3><div class="view-line"><span>Mostura</span><b>${r.agua_mostura||0} L</b></div><div class="view-line"><span>Lavagem</span><b>${r.agua_lavagem||0} L</b></div><div class="view-line view-total"><span>Total</span><b>${n(r.agua_mostura)+n(r.agua_lavagem)} L</b></div></section>
  ${lista('🧪 Correção da água',r.correcoes||[],'g')}
  ${lista('🌾 Maltes',r.maltes||[],'kg')}
  ${lista('🌿 Lúpulos',r.lupulos||[],'g')}
  <section class="view-block"><h3>🧫 Fermento</h3><div class="view-line"><span>${escapeHtml(r.fermento_nome||'Não informado')}</span><b>${r.fermento_pacotes||0} pacotes</b></div></section>
  ${lista('➕ Adjuntos',r.adjuntos||[],'kg')}
  <section class="view-block"><h3>🌡️ Mostura</h3>${rampas.length?rampas.map((x,i)=>`<div class="view-line"><span>Rampa ${i+1}: ${x.temperatura} °C</span><b>${x.tempo_minutos} min</b></div>`).join(''):'<p class="view-empty">Nenhuma rampa cadastrada</p>'}<div class="view-line"><span>Mash out: ${r.mash_out_temperatura||0} °C</span><b>${r.mash_out_tempo||0} min</b></div></section>
  <section class="view-block"><h3>🚿 Lavagem</h3><div class="view-line"><span>Temperatura</span><b>${r.lavagem_temperatura||0} °C</b></div><div class="view-line"><span>Tempo</span><b>${r.lavagem_tempo||0} min</b></div></section>
  <section class="view-block view-wide"><h3>♨️ Fervura e adições</h3><div class="view-line"><span>Tempo total de fervura</span><b>${r.fervura_tempo||0} min</b></div>${adicoes.length?adicoes.map(x=>`<div class="view-line"><span><strong>${x.minutos_para_fim} min para o fim:</strong> ${escapeHtml(x.ingrediente)} (${escapeHtml(x.tipo)})</span><b>${x.quantidade} ${x.unidade}</b></div>`).join(''):'<p class="view-empty">Nenhuma adição cadastrada</p>'}</section>
 </div></div>`;
 eh('voltarReceitas').onclick=()=>renderLista(c);
 eh('editarReceitaView').onclick=()=>abrirForm(c,r);
 }
 function abrirForm(c,r=null){form=r?structuredClone(r):nova();editando=r?.id||null;etapa=0;renderForm(c);}
 const campo=(label,key,unidade='',tipo='number')=>`<label class="recipe-field">${label}<span><input data-key="${key}" type="${tipo}" step="0.01" value="${escapeHtml(form[key]??'')}">${unidade?`<b>${unidade}</b>`:''}</span></label>`;
 function listaIng(key,titulo,unidade){return`<section class="recipe-block"><header><h3>${titulo}</h3><button type="button" data-add="${key}">+ Adicionar item</button></header>${form[key].map((x,i)=>`<div class="recipe-line"><input data-arr="${key}" data-i="${i}" data-k="nome" placeholder="Nome do produto" value="${escapeHtml(x.nome||'')}"><input data-arr="${key}" data-i="${i}" data-k="quantidade" type="number" step="0.001" placeholder="Quantidade" value="${x.quantidade??''}"><b>${unidade}</b><button type="button" data-del="${key}" data-i="${i}">🗑</button></div>`).join('')}<div class="recipe-total">Total: ${form[key].reduce((a,x)=>a+n(x.quantidade),0)} ${unidade}</div></section>`;}
 function renderForm(c){let conteudo='';if(etapa===0)conteudo=`<section class="recipe-block"><h3>📝 Identificação</h3><div class="recipe-cols">${campo('Nome','nome','', 'text')}${campo('Estilo','estilo','', 'text')}${campo('Volume do lote','volume_lote','L')}</div></section><section class="recipe-block"><h3>💧 Água</h3><div class="recipe-cols">${campo('Água da mostura','agua_mostura','L')}${campo('Água da lavagem','agua_lavagem','L')}<div class="recipe-summary">Água total <b>${n(form.agua_mostura)+n(form.agua_lavagem)} L</b></div></div></section>${listaIng('correcoes','🧪 Produtos para correção da água','g')}${listaIng('maltes','🌾 Maltes','kg')}${listaIng('lupulos','🌿 Lúpulos da receita','g')}<section class="recipe-block"><h3>🧫 Fermento</h3><div class="recipe-cols">${campo('Fermento utilizado','fermento_nome','', 'text')}${campo('Quantidade','fermento_pacotes','pacotes')}</div></section>${listaIng('adjuntos','➕ Adjuntos','kg')}`;
 if(etapa===1)conteudo=`<section class="recipe-block"><header><h3>🌡️ Rampas da mostura</h3><button type="button" data-add="rampas">+ Adicionar rampa</button></header>${form.rampas.map((x,i)=>`<div class="recipe-line"><b>Rampa ${i+1}</b><input data-arr="rampas" data-i="${i}" data-k="temperatura" type="number" step="0.01" placeholder="Temperatura" value="${x.temperatura??''}"><b>°C</b><input data-arr="rampas" data-i="${i}" data-k="tempo_minutos" type="number" placeholder="Tempo" value="${x.tempo_minutos??''}"><b>min</b><button type="button" data-del="rampas" data-i="${i}">🗑</button></div>`).join('')}</section><section class="recipe-block"><h3>🔥 Mash out</h3><div class="recipe-cols">${campo('Temperatura','mash_out_temperatura','°C')}${campo('Tempo','mash_out_tempo','min')}</div></section>`;
 if(etapa===2)conteudo=`<section class="recipe-block"><h3>🚿 Lavagem</h3><div class="recipe-cols">${campo('Temperatura','lavagem_temperatura','°C')}${campo('Tempo','lavagem_tempo','min')}<div class="recipe-summary">Água reservada <b>${form.agua_lavagem||0} L</b></div></div></section>`;
 if(etapa===3)conteudo=`<section class="recipe-block"><h3>♨️ Fervura</h3>${campo('Tempo total','fervura_tempo','min')}</section><section class="recipe-block"><header><h3>⏱️ Cronograma de adições</h3><button type="button" data-add="adicoes">+ Ingrediente</button></header>${form.adicoes.map((x,i)=>`<div class="recipe-line"><select data-arr="adicoes" data-i="${i}" data-k="tipo"><option ${x.tipo==='Lupulo'?'selected':''}>Lupulo</option><option ${x.tipo==='Adjunto'?'selected':''}>Adjunto</option></select><input data-arr="adicoes" data-i="${i}" data-k="ingrediente" placeholder="Ingrediente" value="${escapeHtml(x.ingrediente||'')}"><input data-arr="adicoes" data-i="${i}" data-k="quantidade" type="number" placeholder="Qtd." value="${x.quantidade??''}"><select data-arr="adicoes" data-i="${i}" data-k="unidade"><option ${x.unidade==='g'?'selected':''}>g</option><option ${x.unidade==='kg'?'selected':''}>kg</option><option ${x.unidade==='un.'?'selected':''}>un.</option></select><input data-arr="adicoes" data-i="${i}" data-k="minutos_para_fim" type="number" placeholder="Min. para o fim" value="${x.minutos_para_fim??''}"><button type="button" data-del="adicoes" data-i="${i}">🗑</button></div>`).join('')}</section>`;
 c.innerHTML=`<div class="recipe-modal"><div class="recipe-title"><h2>${editando?'Editar':'Nova'} receita</h2><button id="fecharReceita">✕</button></div><nav>${['Receita','Mostura','Lavagem','Fervura'].map((x,i)=>`<button class="${etapa===i?'on':''}" data-step="${i}">${i+1}. ${x}</button>`).join('')}</nav><div class="recipe-body">${conteudo}</div><footer><button class="btn alt" id="anterior" ${etapa===0?'disabled':''}>← Anterior</button>${etapa<3?'<button class="btn" id="proxima">Próxima →</button>':'<button class="btn" id="salvarReceita">💾 Salvar receita</button>'}</footer></div>`;bind(c);}
 function bind(c){c.querySelectorAll('[data-key]').forEach(e=>e.oninput=()=>{form[e.dataset.key]=e.value});c.querySelectorAll('[data-arr]').forEach(e=>e.oninput=()=>{form[e.dataset.arr][+e.dataset.i][e.dataset.k]=e.value});c.querySelectorAll('[data-add]').forEach(e=>e.onclick=()=>{let k=e.dataset.add;form[k].push(k==='rampas'?{temperatura:'',tempo_minutos:''}:k==='adicoes'?{tipo:'Lupulo',ingrediente:'',quantidade:'',unidade:'g',minutos_para_fim:''}:produtosVazios());renderForm(c)});c.querySelectorAll('[data-del]').forEach(e=>e.onclick=()=>{form[e.dataset.del].splice(+e.dataset.i,1);renderForm(c)});c.querySelectorAll('[data-step]').forEach(e=>e.onclick=()=>{etapa=+e.dataset.step;renderForm(c)});eh('fecharReceita').onclick=()=>renderLista(c);eh('anterior').onclick=()=>{etapa--;renderForm(c)};if(eh('proxima'))eh('proxima').onclick=()=>{etapa++;renderForm(c)};if(eh('salvarReceita'))eh('salvarReceita').onclick=()=>salvar(c);}
 async function apagarReceita(c,id){const receita=receitas.find(r=>r.id===id);if(!receita)return;const confirmar=window.confirm(`Apagar a receita "${receita.nome}"? Ingredientes, rampas e adições também serão removidos.`);if(!confirmar)return;const{error}=await supabase.from('receitas').delete().eq('id',id);if(error){alert('Não foi possível apagar a receita: '+error.message);return}receitas=receitas.filter(r=>r.id!==id);renderLista(c);}
 async function salvar(c){if(!form.nome.trim())return alert('Informe o nome da receita.');const base={cervejaria_id:getCervejaria(),usuario_id:getUsuario(),nome:form.nome,estilo:form.estilo||null,volume_lote:n(form.volume_lote)||null,agua_mostura:n(form.agua_mostura),agua_lavagem:n(form.agua_lavagem),fermento_nome:form.fermento_nome||null,fermento_pacotes:n(form.fermento_pacotes)||null,mash_out_temperatura:n(form.mash_out_temperatura)||null,mash_out_tempo:n(form.mash_out_tempo)||null,lavagem_temperatura:n(form.lavagem_temperatura)||null,lavagem_tempo:n(form.lavagem_tempo)||null,fervura_tempo:n(form.fervura_tempo)||null,atualizado_em:new Date().toISOString()};let q=editando?supabase.from('receitas').update(base).eq('id',editando).select().single():supabase.from('receitas').insert(base).select().single();let{data:r,error}=await q;if(error)return alert(error.message);for(const t of ['receita_ingredientes','receita_rampas','receita_fervura_adicoes'])await supabase.from(t).delete().eq('receita_id',r.id);let ing=[];[['maltes','Malte','kg'],['lupulos','Lupulo','g'],['adjuntos','Adjunto','kg'],['correcoes','CorrecaoAgua','g']].forEach(([k,cat,un])=>form[k].forEach((x,i)=>{if(x.nome&&n(x.quantidade)>=0)ing.push({receita_id:r.id,cervejaria_id:getCervejaria(),usuario_id:getUsuario(),categoria:cat,nome:x.nome,quantidade:n(x.quantidade),unidade:un,ordem:i})}));if(ing.length)await supabase.from('receita_ingredientes').insert(ing);if(form.rampas.length)await supabase.from('receita_rampas').insert(form.rampas.filter(x=>x.temperatura!==''&&x.tempo_minutos!=='').map((x,i)=>({receita_id:r.id,cervejaria_id:getCervejaria(),usuario_id:getUsuario(),ordem:i+1,temperatura:n(x.temperatura),tempo_minutos:n(x.tempo_minutos)})));if(form.adicoes.length)await supabase.from('receita_fervura_adicoes').insert(form.adicoes.filter(x=>x.ingrediente).map((x,i)=>({receita_id:r.id,cervejaria_id:getCervejaria(),usuario_id:getUsuario(),tipo:x.tipo,ingrediente:x.ingrediente,quantidade:n(x.quantidade),unidade:x.unidade,minutos_para_fim:n(x.minutos_para_fim),ordem:i})));await carregar();renderLista(c);}
 return{abrir};
}
